<a href="https://colab.research.google.com/github/Gkcoli/MLThings/blob/main/Draft%20Midterms_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Imports

In [116]:
import pandas as pd
from sklearn.metrics import mean_squared_error

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from scipy.stats import pearsonr
import statsmodels.api as sm
from sklearn.preprocessing import LabelEncoder

#Dataset File

In [117]:
dataset_url = 'https://github.com/robitussin/CCMACLRL_EXAM/blob/a46a4e2a001dedaefc9b431d480b508ce86c2d96/datasets/train.csv?raw=true'
df = pd.read_csv(dataset_url)

#Test File

In [118]:
test_url = 'https://github.com/robitussin/CCMACLRL_EXAM/blob/a46a4e2a001dedaefc9b431d480b508ce86c2d96/datasets/test.csv?raw=true'
dt=pd.read_csv(test_url)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188533 entries, 0 to 188532
Data columns (total 13 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            188533 non-null  int64
 1   brand         188533 non-null  object
 2   model         188533 non-null  object
 3   model_year    188533 non-null  int64
 4   milage        188533 non-null  int64
 5   fuel_type     183450 non-null  object
 6   engine        188533 non-null  object
 7   transmission  188533 non-null  object
 8   ext_col       188533 non-null  object
 9   int_col       188533 non-null  object
 10  accident      186081 non-null  object
 11  clean_title   167114 non-null  object
 12  price         188533 non-null  int64
dtypes: int64(4), object(9)
memory usage: 18.7+ MB

#Sample Submission File

In [119]:
sample_submission_url = 'https://github.com/robitussin/CCMACLRL_EXAM/blob/a46a4e2a001dedaefc9b431d480b508ce86c2d96/datasets/sample_submission.csv?raw=true'

sf=pd.read_csv(sample_submission_url)

#Checkdata

In [120]:
df.head()

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,0,MINI,Cooper S Base,2007,213000,Gasoline,172.0HP 1.6L 4 Cylinder Engine Gasoline Fuel,A/T,Yellow,Gray,None reported,Yes,4200
1,1,Lincoln,LS V8,2002,143250,Gasoline,252.0HP 3.9L 8 Cylinder Engine Gasoline Fuel,A/T,Silver,Beige,At least 1 accident or damage reported,Yes,4999
2,2,Chevrolet,Silverado 2500 LT,2002,136731,E85 Flex Fuel,320.0HP 5.3L 8 Cylinder Engine Flex Fuel Capab...,A/T,Blue,Gray,None reported,Yes,13900
3,3,Genesis,G90 5.0 Ultimate,2017,19500,Gasoline,420.0HP 5.0L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,None reported,Yes,45000
4,4,Mercedes-Benz,Metris Base,2021,7388,Gasoline,208.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,7-Speed A/T,Black,Beige,None reported,Yes,97500

In [121]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188533 entries, 0 to 188532
Data columns (total 13 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            188533 non-null  int64
 1   brand         188533 non-null  object
 2   model         188533 non-null  object
 3   model_year    188533 non-null  int64
 4   milage        188533 non-null  int64
 5   fuel_type     183450 non-null  object
 6   engine        188533 non-null  object
 7   transmission  188533 non-null  object
 8   ext_col       188533 non-null  object
 9   int_col       188533 non-null  object
 10  accident      186081 non-null  object
 11  clean_title   167114 non-null  object
 12  price         188533 non-null  int64
dtypes: int64(4), object(9)
memory usage: 18.7+ MB

In [122]:
df.duplicated().sum()

0

In [123]:
df.dropna(inplace=True)

In [124]:
df.isnull().sum()

id              0
brand           0
model           0
model_year      0
milage          0
fuel_type       0
engine          0
transmission    0
ext_col         0
int_col         0
accident        0
clean_title     0
price           0
dtype: int64

In [125]:
df.describe()

                  id     model_year         milage         price
count  162610.000000  162610.000000  162610.000000  1.626100e+05
mean    94197.039137    2015.158822   71105.487086  4.081699e+04
std     54467.770815       5.699531   50157.874111  7.653857e+04
min         0.000000    1974.000000     100.000000  2.000000e+03
25%     47026.250000    2012.000000   29000.000000  1.570000e+04
50%     94139.000000    2016.000000   64300.000000  2.850000e+04
75%    141421.750000    2019.000000  101000.000000  4.699900e+04
max    188532.000000    2024.000000  405000.000000  2.954083e+06

In [126]:
df.sample(20)

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
125710,125710,Lexus,IS 300 Base,2010,106000,Gasoline,255.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,A/T,Gray,Black,At least 1 accident or damage reported,Yes,12900
8986,8986,Porsche,911 Carrera,2023,7000,Gasoline,379.0HP 3.0L Flat 6 Cylinder Engine Gasoline Fuel,8-Speed A/T,Silver,Black,None reported,Yes,47999
188369,188369,Audi,S4 3.0T Premium Plus,2020,18100,Gasoline,349.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,8-Speed A/T,Gray,Black,None reported,Yes,41900
8391,8391,Nissan,Pathfinder S,2016,101600,Gasoline,284.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,6-Speed A/T,Black,Black,None reported,Yes,17500
17704,17704,Land,Rover Range Rover Sport Supercharged HSE,2015,38718,Gasoline,340.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,8-Speed A/T,Blue,Brown,None reported,Yes,38900
66250,66250,Mercedes-Benz,AMG G 63 Base,2022,4590,Gasoline,577.0HP 4.0L 8 Cylinder Engine Gasoline Fuel,A/T,White,Black,None reported,Yes,54000
145816,145816,Ford,Edge Titanium,2015,130307,Gasoline,245.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,6-Speed A/T,White,–,None reported,Yes,7500
66248,66248,Land,Rover Range Rover Sport HSE,2016,54323,Gasoline,340.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,8-Speed A/T,White,Black,None reported,Yes,19190
178132,178132,Ford,Expedition Platinum,2018,61341,Gasoline,5.3L V8 16V GDI OHV,10-Speed Automatic,Tan,Ebony,None reported,Yes,55460
62709,62709,Ford,F-250 XLT Crew Cab Super Duty,2003,82963,Gasoline,300.0HP 5.4L 8 Cylinder Engine Gasoline Fuel,A/T,Gray,Black,At least 1 accident or damage reported,Yes,18000
105167,105167,Porsche,Cayenne S,2015,124000,Gasoline,420.0HP 3.6L V6 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,White,Beige,None reported,Yes,26000
58855,58855,RAM,ProMaster 2500 Window Van High Roof,2014,124400,Gasoline,280.0HP 3.6L V6 Cylinder Engine Gasoline Fuel,6-Speed A/T,White,Gray,At least 1 accident or damage reported,Yes,22500
68780,68780,Land,Rover Range Rover Sport Supercharged HSE,2016,112000,Gasoline,340.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,A/T,Black,Black,None reported,Yes,15000
25717,25717,Mercedes-Benz,E-Class E 350 4MATIC,2013,58664,Gasoline,268.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,7-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,20000
68993,68993,Mercedes-Benz,AMG C 43 Base 4MATIC,2017,53500,Gasoline,362.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,9-Speed A/T,Gray,Black,None reported,Yes,28000
112704,112704,Ford,Expedition Max King Ranch,2021,7089,Gasoline,3.5L V6 24V PDI DOHC Twin Turbo,8-Speed Automatic,Black,Sandstone,None reported,Yes,59203
62467,62467,Nissan,Armada SL,2021,53677,Gasoline,400.0HP 5.6L 8 Cylinder Engine Gasoline Fuel,7-Speed A/T,Black,Brown,None reported,Yes,39750
182763,182763,Mercedes-Benz,C-Class C 300 4MATIC,2018,80134,Gasoline,241.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,White,Black,None reported,Yes,19250
163917,163917,Porsche,Macan S,2016,61258,Gasoline,340.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,7-Speed A/T,Black,Red,None reported,Yes,41900
160008,160008,BMW,M4 Base,2018,7300,Gasoline,425.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,7-Speed A/T,Blue,Orange,None reported,Yes,50000

#Import Datetime

In [127]:
from datetime import datetime

current_year = datetime.now().year
df['car_age'] = current_year - df['model_year'].astype(str).str.split('-', expand=True)[0].astype(int)
df.head()

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price,car_age
0,0,MINI,Cooper S Base,2007,213000,Gasoline,172.0HP 1.6L 4 Cylinder Engine Gasoline Fuel,A/T,Yellow,Gray,None reported,Yes,4200,17
1,1,Lincoln,LS V8,2002,143250,Gasoline,252.0HP 3.9L 8 Cylinder Engine Gasoline Fuel,A/T,Silver,Beige,At least 1 accident or damage reported,Yes,4999,22
2,2,Chevrolet,Silverado 2500 LT,2002,136731,E85 Flex Fuel,320.0HP 5.3L 8 Cylinder Engine Flex Fuel Capab...,A/T,Blue,Gray,None reported,Yes,13900,22
3,3,Genesis,G90 5.0 Ultimate,2017,19500,Gasoline,420.0HP 5.0L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,None reported,Yes,45000,7
4,4,Mercedes-Benz,Metris Base,2021,7388,Gasoline,208.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,7-Speed A/T,Black,Beige,None reported,Yes,97500,3

# Extract Luxury Brands

In [128]:
def extract_luxury(brand):
  luxury_brands = [
      'Lexus', 'Audi', 'BMW', 'Mercedes-Benz', 'Jaguar', 'Porsche', 'Rolls-Royce', 'Lamborghini',
      'Maserati', 'Ferrari', 'McLaren', 'Bentley', 'Tesla', 'Cadillac', 'Volvo', 'Land Rover', 'Genesis'
  ]
  return "Yes" if any(lux_brand.lower() in brand.lower() for lux_brand in luxury_brands) else "No"

df['is_luxury'] = df['brand'].apply(extract_luxury)

#Transmission Mapping

In [129]:
transmission_mapping = {
   'A/T': 'A/T', 'Transmission w/Dual Shift Mode': 'DCT', '7-Speed A/T': 'A/T',
   '8-Speed A/T': 'A/T', '10-Speed Automatic': 'A/T', '6-Speed A/T': 'A/T',
   '10-Speed A/T': 'A/T', '9-Speed A/T': 'A/T', '9-Speed Automatic': 'A/T',
   '5-Speed A/T': 'A/T', '8-Speed Automatic': 'A/T', 'CVT Transmission': 'CVT',
   '5-Speed M/T': 'M/T', 'M/T': 'M/T', '6-Speed M/T': 'M/T', '6-Speed Automatic': 'A/T',
   '4-Speed Automatic': 'A/T', '7-Speed M/T': 'M/T', 'Automatic': 'A/T',
   '4-Speed A/T': 'A/T', '2-Speed A/T': 'A/T', '6-Speed Manual': 'M/T',
   'Transmission Overdrive Switch': 'A/T', '8-Speed Automatic with Auto-Shift': 'A/T',
   '7-Speed Automatic with Auto-Shift': 'A/T', 'Automatic CVT': 'CVT', '1-Speed A/T': 'A/T',
   '6-Speed Electronically Controlled Automatic with O': 'A/T', 'F': None,
   '8-Speed Manual': 'M/T', '6-Speed Automatic with Auto-Shift': 'A/T',
   '7-Speed Automatic': 'A/T', '7-Speed Manual': 'M/T', '7-Speed': None,
   'Single-Speed Fixed Gear': None, '8-SPEED AT': 'A/T',
   '10-Speed Automatic with Overdrive': 'A/T', '2-Speed Automatic': 'A/T',
   'CVT-F': 'CVT', '5-Speed Automatic': 'A/T', '–': None,
   '7-Speed DCT Automatic': 'DCT', 'Manual': 'M/T', '2': None,
   '1-Speed Automatic': 'A/T', '6-Speed': None,
   'SCHEDULED FOR OR IN PRODUCTION': None, 'Variable': None,
   '9-Speed Automatic with Auto-Shift': 'A/T', '6 Speed Mt': 'M/T',
   '6 Speed At/Mt': 'DCT', '8-SPEED A/T': 'A/T'
}

In [130]:
# Apply transmission mappings to the 'transmission' column
df['transmission'] = df['transmission'].replace(transmission_mapping)
# Accident data mapping
df['accident'] = df['accident'].replace({
   'None reported': 'No'
})

In [131]:
df

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price,car_age,is_luxury
0,0,MINI,Cooper S Base,2007,213000,Gasoline,172.0HP 1.6L 4 Cylinder Engine Gasoline Fuel,A/T,Yellow,Gray,No,Yes,4200,17,No
1,1,Lincoln,LS V8,2002,143250,Gasoline,252.0HP 3.9L 8 Cylinder Engine Gasoline Fuel,A/T,Silver,Beige,At least 1 accident or damage reported,Yes,4999,22,No
2,2,Chevrolet,Silverado 2500 LT,2002,136731,E85 Flex Fuel,320.0HP 5.3L 8 Cylinder Engine Flex Fuel Capab...,A/T,Blue,Gray,No,Yes,13900,22,No
3,3,Genesis,G90 5.0 Ultimate,2017,19500,Gasoline,420.0HP 5.0L 8 Cylinder Engine Gasoline Fuel,DCT,Black,Black,No,Yes,45000,7,Yes
4,4,Mercedes-Benz,Metris Base,2021,7388,Gasoline,208.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,Black,Beige,No,Yes,97500,3,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
188527,188527,Chevrolet,Camaro Z28,1999,110000,Gasoline,310.0HP 5.7L 8 Cylinder Engine Gasoline Fuel,A/T,White,Gray,No,Yes,14500,25,No
188528,188528,Cadillac,Escalade ESV Platinum,2017,49000,Gasoline,420.0HP 6.2L 8 Cylinder Engine Gasoline Fuel,DCT,White,Beige,No,Yes,27500,7,Yes
188529,188529,Mercedes-Benz,AMG C 43 AMG C 43 4MATIC,2018,28600,Gasoline,385.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,A/T,White,Black,At least 1 accident or damage reported,Yes,30000,6,Yes
188530,188530,Mercedes-Benz,AMG GLC 63 Base 4MATIC,2021,13650,Gasoline,469.0HP 4.0L 8 Cylinder Engine Gasoline Fuel,A/T,White,Black,No,Yes,86900,3,Yes
188532,188532,Porsche,Macan Base,2016,59500,Gasoline,252.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,DCT,White,Black,No,Yes,28995,8,Yes

In [132]:
df.isnull().sum()

id               0
brand            0
model            0
model_year       0
milage           0
fuel_type        0
engine           0
transmission    92
ext_col          0
int_col          0
accident         0
clean_title      0
price            0
car_age          0
is_luxury        0
dtype: int64

In [133]:
label_encoder = LabelEncoder()
df['brand'] = label_encoder.fit_transform(df['brand'])

In [134]:
drop_col=['id','ext_col','int_col', 'fuel_type', 'engine', 'model', 'clean_title']
# Check if all columns exist before dropping
if all(col in df.columns for col in drop_col):
    df.drop(drop_col,inplace=True,axis=1)
else:
    # Find the missing columns
    missing_cols = [col for col in drop_col if col not in df.columns]
    print(f"Error: Columns not found in DataFrame: {missing_cols}")
object_columns = df.select_dtypes(include=['object']).columns

In [135]:
drop_col=['id','ext_col','int_col', 'fuel_type', 'engine', 'model', 'clean_title']

if all(col in df.columns for col in drop_col):
    df.drop(drop_col,inplace=True,axis=1)
else:

    missing_cols = [col for col in drop_col if col not in df.columns]
    print(f"Error: Columns not found in DataFrame: {missing_cols}")
object_columns = df.select_dtypes(include=['object']).columns

if 'transmission' in df.columns:
    print("`transmission` column exists in the DataFrame.")
else:
    print("`transmission` column does not exist in the DataFrame.")

Error: Columns not found in DataFrame: ['id', 'ext_col', 'int_col', 'fuel_type', 'engine', 'model', 'clean_title']
`transmission` column exists in the DataFrame.

In [136]:
df = pd.get_dummies(df, columns = object_columns)

In [137]:
df

,brand,model_year,milage,price,car_age,transmission_A/T,transmission_CVT,transmission_DCT,transmission_M/T,accident_At least 1 accident or damage reported,accident_No,is_luxury_No,is_luxury_Yes
0,31,2007,213000,4200,17,True,False,False,False,False,True,True,False
1,28,2002,143250,4999,22,True,False,False,False,True,False,True,False
2,9,2002,136731,13900,22,True,False,False,False,False,True,True,False
3,16,2017,19500,45000,7,False,False,True,False,False,True,False,True
4,36,2021,7388,97500,3,True,False,False,False,False,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
188527,9,1999,110000,14500,25,True,False,False,False,False,True,True,False
188528,8,2017,49000,27500,7,False,False,True,False,False,True,False,True
188529,36,2018,28600,30000,6,True,False,False,False,True,False,False,True
188530,36,2021,13650,86900,3,True,False,False,False,False,True,False,True
188532,43,2016,59500,28995,8,False,False,True,False,False,True,False,True

In [138]:
from sklearn.preprocessing import MinMaxScaler

non_boolean_numerical_features = ["model_year",'milage','price','car_age']
scaler = MinMaxScaler()


df[non_boolean_numerical_features] = scaler.fit_transform(df[non_boolean_numerical_features])

#Test

In [139]:
X = df.drop('price', axis=1)
y = df['price']

In [159]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [155]:
from sklearn.linear_model import LinearRegression
linear_reg.fit(X_train, y_train)

LinearRegression()

In [156]:
y_pred_train = linear_reg.predict(X_train)
y_pred_test = linear_reg.predict(X_test)

In [157]:
#Import the necessary functions from sklearn
from sklearn.metrics import mean_squared_error, r2_score

train_mse = mean_squared_error(y_train, y_pred_train)
train_r2 = r2_score(y_train, y_pred_train)


test_mse = mean_squared_error(y_test, y_pred_test)
test_r2 = r2_score(y_test, y_pred_test)

print(f"Training MSE:{train_mse}")
print(f"Testing MSE:{test_mse}")
print(f"Training R2 Score:{train_r2}")
print(f"Testing R2 Score:{test_r2}")

Training MSE:0.0005903874129242107
Testing MSE:0.0007044659209532208
Training R2 Score:0.0910497630740903
Testing R2 Score:0.07660188821716551

In [158]:
model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

mean_squared_error = mean_squared_error(y_test, y_pred, squared=False)

In [149]:
# Calculate car age
dt['car_age'] = current_year - dt['model_year'].astype(str).str.split('-', expand=True)[0].astype(int)

# Transmission columns conversion
transmission_columns = ['transmission_A/T', 'transmission_CVT', 'transmission_DCT', 'transmission_M/T']
for col in transmission_columns:
    if col in dt.columns:
        dt[col] = pd.to_numeric(dt[col], errors='coerce').fillna(0).astype(int)

# Binary columns conversion
binary_columns = ['accident_No', 'accident_Yes', 'is_luxury_No', 'is_luxury_Yes']
for col in binary_columns:
    if col in dt.columns:
        dt[col] = pd.to_numeric(dt[col], errors='coerce').fillna(0).astype(int)

# Dropping columns
columns_to_drop = ['accident', 'clean_title', 'engine', 'ext_col', 'fuel_type', 'id', 'int_col', 'model', 'transmission']
dt.drop(columns=[col for col in columns_to_drop if col in dt.columns], axis=1, inplace=True)

In [150]:
label_encoder = LabelEncoder()
dt['brand'] = label_encoder.fit_transform(dt['brand'])

In [151]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 162610 entries, 0 to 188532
Data columns (total 13 columns):
 #   Column                                           Non-Null Count   Dtype
---  ------                                           --------------   -----
 0   brand                                            162610 non-null  int64
 1   model_year                                       162610 non-null  float64
 2   milage                                           162610 non-null  float64
 3   price                                            162610 non-null  float64
 4   car_age                                          162610 non-null  float64
 5   transmission_A/T                                 162610 non-null  bool
 6   transmission_CVT                                 162610 non-null  bool
 7   transmission_DCT                                 162610 non-null  bool
 8   transmission_M/T                                 162610 non-null  bool
 9   accident_At least 1 accident or damage reported  162610 non-null  bool
 10  accident_No                                      162610 non-null  bool
 11  is_luxury_No                                     162610 non-null  bool
 12  is_luxury_Yes                                    162610 non-null  bool
dtypes: bool(8), float64(4), int64(1)
memory usage: 8.7 MB

In [152]:
dt.fillna(0, inplace=True)