<a href="https://colab.research.google.com/github/Gkcoli/MLThings/blob/main/Draft%20Midterms_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Imports

In [307]:
import pandas as pd
from sklearn.metrics import mean_squared_error

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from scipy.stats import pearsonr
import statsmodels.api as sm
from sklearn.preprocessing import LabelEncoder

#Dataset File

In [308]:
dataset_url = 'https://github.com/robitussin/CCMACLRL_EXAM/blob/a46a4e2a001dedaefc9b431d480b508ce86c2d96/datasets/train.csv?raw=true'
df = pd.read_csv(dataset_url)

#Test File

In [309]:
test_url = 'https://github.com/robitussin/CCMACLRL_EXAM/blob/a46a4e2a001dedaefc9b431d480b508ce86c2d96/datasets/test.csv?raw=true'
dt=pd.read_csv(test_url)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188533 entries, 0 to 188532
Data columns (total 13 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            188533 non-null  int64
 1   brand         188533 non-null  object
 2   model         188533 non-null  object
 3   model_year    188533 non-null  int64
 4   milage        188533 non-null  int64
 5   fuel_type     183450 non-null  object
 6   engine        188533 non-null  object
 7   transmission  188533 non-null  object
 8   ext_col       188533 non-null  object
 9   int_col       188533 non-null  object
 10  accident      186081 non-null  object
 11  clean_title   167114 non-null  object
 12  price         188533 non-null  int64
dtypes: int64(4), object(9)
memory usage: 18.7+ MB

#Sample Submission File

In [310]:
sample_submission_url = 'https://github.com/robitussin/CCMACLRL_EXAM/blob/a46a4e2a001dedaefc9b431d480b508ce86c2d96/datasets/sample_submission.csv?raw=true'

sf=pd.read_csv(sample_submission_url)

#Checkdata

In [311]:
df.head()

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,0,MINI,Cooper S Base,2007,213000,Gasoline,172.0HP 1.6L 4 Cylinder Engine Gasoline Fuel,A/T,Yellow,Gray,None reported,Yes,4200
1,1,Lincoln,LS V8,2002,143250,Gasoline,252.0HP 3.9L 8 Cylinder Engine Gasoline Fuel,A/T,Silver,Beige,At least 1 accident or damage reported,Yes,4999
2,2,Chevrolet,Silverado 2500 LT,2002,136731,E85 Flex Fuel,320.0HP 5.3L 8 Cylinder Engine Flex Fuel Capab...,A/T,Blue,Gray,None reported,Yes,13900
3,3,Genesis,G90 5.0 Ultimate,2017,19500,Gasoline,420.0HP 5.0L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,None reported,Yes,45000
4,4,Mercedes-Benz,Metris Base,2021,7388,Gasoline,208.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,7-Speed A/T,Black,Beige,None reported,Yes,97500

In [312]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188533 entries, 0 to 188532
Data columns (total 13 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            188533 non-null  int64
 1   brand         188533 non-null  object
 2   model         188533 non-null  object
 3   model_year    188533 non-null  int64
 4   milage        188533 non-null  int64
 5   fuel_type     183450 non-null  object
 6   engine        188533 non-null  object
 7   transmission  188533 non-null  object
 8   ext_col       188533 non-null  object
 9   int_col       188533 non-null  object
 10  accident      186081 non-null  object
 11  clean_title   167114 non-null  object
 12  price         188533 non-null  int64
dtypes: int64(4), object(9)
memory usage: 18.7+ MB

In [313]:
df.duplicated().sum()

0

In [314]:
df.dropna(inplace=True)

In [315]:
df.isnull().sum()

id              0
brand           0
model           0
model_year      0
milage          0
fuel_type       0
engine          0
transmission    0
ext_col         0
int_col         0
accident        0
clean_title     0
price           0
dtype: int64

In [316]:
df.describe()

                  id     model_year         milage         price
count  162610.000000  162610.000000  162610.000000  1.626100e+05
mean    94197.039137    2015.158822   71105.487086  4.081699e+04
std     54467.770815       5.699531   50157.874111  7.653857e+04
min         0.000000    1974.000000     100.000000  2.000000e+03
25%     47026.250000    2012.000000   29000.000000  1.570000e+04
50%     94139.000000    2016.000000   64300.000000  2.850000e+04
75%    141421.750000    2019.000000  101000.000000  4.699900e+04
max    188532.000000    2024.000000  405000.000000  2.954083e+06

In [317]:
df.sample(20)

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
64499,64499,Ford,F-250 Lariat,2016,67522,Diesel,440.0HP 6.7L 8 Cylinder Engine Diesel Fuel,6-Speed A/T,White,Black,None reported,Yes,27995
144214,144214,Land,Rover Discovery HSE LUXURY,2019,57918,Gasoline,340.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,8-Speed A/T,White,Black,None reported,Yes,26900
172909,172909,Ford,Transit-350 XLT,2018,71000,Gasoline,310.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,A/T,White,Gray,At least 1 accident or damage reported,Yes,26500
29317,29317,Cadillac,CTS Luxury,2012,60000,Gasoline,270.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,24500
146637,146637,Audi,A6 2.0T Sport,2018,98000,Gasoline,252.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,White,Black,None reported,Yes,26500
12767,12767,Cadillac,ATS 2.0L Turbo Luxury,2016,90581,Gasoline,272.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,6-Speed A/T,White,Beige,None reported,Yes,16500
178960,178960,BMW,M5 Base,2015,67400,Gasoline,560.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Blue,Black,None reported,Yes,32500
18935,18935,Mercedes-Benz,C-Class C 300 4MATIC Sport,2014,90189,Gasoline,248.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,A/T,White,–,At least 1 accident or damage reported,Yes,13000
168776,168776,McLaren,720S Performance,2020,8228,Gasoline,710.0HP 4.0L 8 Cylinder Engine Gasoline Fuel,A/T,Orange,Black,None reported,Yes,188500
102396,102396,Porsche,911 Turbo S,2022,14739,Gasoline,4.0L H6 24V GDI DOHC,7-Speed Automatic with Auto-Shift,Tango Red Metallic,Black,None reported,Yes,244896
25470,25470,Genesis,G70 3.3T Advanced,2019,89987,Gasoline,365.0HP 3.3L V6 Cylinder Engine Gasoline Fuel,A/T,Black,Black,At least 1 accident or damage reported,Yes,31000
11726,11726,Subaru,Outback 2.5i Premium,2013,116000,Gasoline,173.0HP 2.5L 4 Cylinder Engine Gasoline Fuel,6-Speed A/T,Black,Black,None reported,Yes,15500
179893,179893,Chevrolet,Corvette Stingray w/3LT,2021,12000,Gasoline,490.0HP 6.2L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Yellow,Black,None reported,Yes,33500
67260,67260,Chevrolet,Suburban 1500 LTZ,2007,153818,Gasoline,355.0HP 5.3L 8 Cylinder Engine Gasoline Fuel,6-Speed A/T,Silver,Black,None reported,Yes,15500
23790,23790,Land,Rover Range Rover Evoque R-Dynamic HSE,2013,122000,Gasoline,240.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,9-Speed A/T,Blue,Black,None reported,Yes,11500
28609,28609,Audi,A5 2.0T Premium Plus,2015,73000,Gasoline,220.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,White,Brown,At least 1 accident or damage reported,Yes,13000
69549,69549,Lincoln,MKZ Base,2007,153350,Gasoline,250.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,A/T,Red,Beige,None reported,Yes,14200
47401,47401,BMW,M4 Base,2019,43000,Gasoline,425.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,Transmission w/Dual Shift Mode,Black,Black,None reported,Yes,41900
77110,77110,Lexus,CT 200h Premium,2012,109000,Hybrid,134.0HP 1.8L 4 Cylinder Engine Gas/Electric Hy...,A/T,Black,Black,None reported,Yes,6700
74588,74588,Mazda,Mazda6 i Touring,2016,119500,Gasoline,184.0HP 2.5L 4 Cylinder Engine Gasoline Fuel,6-Speed M/T,Blue,Black,None reported,Yes,15499

#Import Datetime

In [318]:
from datetime import datetime

current_year = datetime.now().year
df['car_age'] = current_year - df['model_year'].astype(str).str.split('-', expand=True)[0].astype(int)

# Extract Luxury Brands

In [319]:
def extract_luxury(brand):
   luxury_yes = [
   'Lexus','Audi','BMW','Mercedes-Benz','Jaguar',
   'Porsche','Rolls-Royce','Lamborghini','Maserati',
   'Ferrari', 'McLaren','Bentley','Tesla', 'Cadillac',
   'McLaren','Volvo','Land Rover', 'Genesis',
]
   Yes = "Yes"
   No = "No"
   for is_luxury in luxury_yes:
       if is_luxury.lower() in brand.lower():
           return Yes
   return No
   df['is_luxury'] = df['brand'].apply(extract_luxury)

#Transmission Mapping

In [320]:
# Check if the 'transmission' column exists in the DataFrame.
if 'transmission' in df.columns:
    df['transmission'] = df['transmission'].replace({
       'A/T': 'A/T',
       'Transmission w/Dual Shift Mode': 'DCT','7-Speed A/T': 'A/T',
       '8-Speed A/T': 'A/T','10-Speed Automatic': 'A/T',
       '6-Speed A/T': 'A/T','10-Speed A/T': 'A/T',
       '9-Speed A/T': 'A/T','9-Speed Automatic': 'A/T',
       '5-Speed A/T': 'A/T','8-Speed Automatic': 'A/T',
       'CVT Transmission': 'CVT','5-Speed M/T': 'M/T',
       'M/T': 'M/T','6-Speed M/T': 'M/T',
       '6-Speed Automatic': 'A/T','4-Speed Automatic': 'A/T',
       '7-Speed M/T': 'M/T','Automatic': 'A/T',
       '4-Speed A/T': 'A/T','2-Speed A/T': 'A/T',
       '6-Speed Manual': 'M/T', 'Transmission Overdrive Switch': 'A/T',
       '8-Speed Automatic with Auto-Shift': 'A/T',
       '7-Speed Automatic with Auto-Shift': 'A/T',
       'Automatic CVT': 'CVT',
       '1-Speed A/T': 'A/T',
       '6-Speed Electronically Controlled Automatic with O': 'A/T',
       'F': None,
       '8-Speed Manual': 'M/T',
       '6-Speed Automatic with Auto-Shift': 'A/T',
       '7-Speed Automatic': 'A/T',
       '7-Speed Manual': 'M/T',
       '7-Speed': None,
       'Single-Speed Fixed Gear': None,
       '8-SPEED AT': 'A/T',
       '10-Speed Automatic with Overdrive': 'A/T',
       '2-Speed Automatic': 'A/T',
       'CVT-F': 'CVT',
       '5-Speed Automatic': 'A/T',
       '–': None,
       '7-Speed DCT Automatic': 'DCT',
       'Manual': 'M/T',
       '2': None,
       '1-Speed Automatic': 'A/T',
       '6-Speed': None,
       'SCHEDULED FOR OR IN PRODUCTION': None,
       'Variable': None,
       '9-Speed Automatic with Auto-Shift': 'A/T',
       '6 Speed Mt': 'M/T',
       '6 Speed At/Mt': 'DCT',
       '8-SPEED A/T': 'A/T'
    })
else:

    print("Column 'transmission' not found in DataFrame.")

In [321]:
if 'accident' in df.columns:
    df['accident'] = df['accident'].replace({
        'None reported': 'No',
        'At least 1 accident or damage reported': 'Yes',
    })
else:
    print("Column 'accident' not found in DataFrame.")

In [322]:
df

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price,car_age
0,0,MINI,Cooper S Base,2007,213000,Gasoline,172.0HP 1.6L 4 Cylinder Engine Gasoline Fuel,A/T,Yellow,Gray,No,Yes,4200,17
1,1,Lincoln,LS V8,2002,143250,Gasoline,252.0HP 3.9L 8 Cylinder Engine Gasoline Fuel,A/T,Silver,Beige,Yes,Yes,4999,22
2,2,Chevrolet,Silverado 2500 LT,2002,136731,E85 Flex Fuel,320.0HP 5.3L 8 Cylinder Engine Flex Fuel Capab...,A/T,Blue,Gray,No,Yes,13900,22
3,3,Genesis,G90 5.0 Ultimate,2017,19500,Gasoline,420.0HP 5.0L 8 Cylinder Engine Gasoline Fuel,DCT,Black,Black,No,Yes,45000,7
4,4,Mercedes-Benz,Metris Base,2021,7388,Gasoline,208.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,Black,Beige,No,Yes,97500,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
188527,188527,Chevrolet,Camaro Z28,1999,110000,Gasoline,310.0HP 5.7L 8 Cylinder Engine Gasoline Fuel,A/T,White,Gray,No,Yes,14500,25
188528,188528,Cadillac,Escalade ESV Platinum,2017,49000,Gasoline,420.0HP 6.2L 8 Cylinder Engine Gasoline Fuel,DCT,White,Beige,No,Yes,27500,7
188529,188529,Mercedes-Benz,AMG C 43 AMG C 43 4MATIC,2018,28600,Gasoline,385.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,A/T,White,Black,Yes,Yes,30000,6
188530,188530,Mercedes-Benz,AMG GLC 63 Base 4MATIC,2021,13650,Gasoline,469.0HP 4.0L 8 Cylinder Engine Gasoline Fuel,A/T,White,Black,No,Yes,86900,3
188532,188532,Porsche,Macan Base,2016,59500,Gasoline,252.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,DCT,White,Black,No,Yes,28995,8

In [323]:
df.isnull().sum()

id               0
brand            0
model            0
model_year       0
milage           0
fuel_type        0
engine           0
transmission    92
ext_col          0
int_col          0
accident         0
clean_title      0
price            0
car_age          0
dtype: int64

In [324]:
label_encoder = LabelEncoder()
df['brand'] = label_encoder.fit_transform(df['brand'])

In [325]:
drop_col=['id','ext_col','int_col', 'fuel_type', 'engine', 'model', 'clean_title']
# Check if all columns exist before dropping
if all(col in df.columns for col in drop_col):
    df.drop(drop_col,inplace=True,axis=1)
else:
    # Find the missing columns
    missing_cols = [col for col in drop_col if col not in df.columns]
    print(f"Error: Columns not found in DataFrame: {missing_cols}")
object_columns = df.select_dtypes(include=['object']).columns

In [326]:
for column in object_columns:
   unique_values = df[column].unique()
   print(f"Unique values in '{column}':")
   print(unique_values)
   print()

Unique values in 'transmission':
['A/T' 'DCT' 'CVT' 'M/T' None]

Unique values in 'accident':
['No' 'Yes']

In [327]:
df = pd.get_dummies(df, columns = object_columns)

In [328]:
df

,brand,model_year,milage,price,car_age,transmission_A/T,transmission_CVT,transmission_DCT,transmission_M/T,accident_No,accident_Yes
0,31,2007,213000,4200,17,True,False,False,False,True,False
1,28,2002,143250,4999,22,True,False,False,False,False,True
2,9,2002,136731,13900,22,True,False,False,False,True,False
3,16,2017,19500,45000,7,False,False,True,False,True,False
4,36,2021,7388,97500,3,True,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...
188527,9,1999,110000,14500,25,True,False,False,False,True,False
188528,8,2017,49000,27500,7,False,False,True,False,True,False
188529,36,2018,28600,30000,6,True,False,False,False,False,True
188530,36,2021,13650,86900,3,True,False,False,False,True,False
188532,43,2016,59500,28995,8,False,False,True,False,True,False

In [329]:
from sklearn.preprocessing import MinMaxScaler

non_boolean_numerical_features = ["model_year",'milage','price','car_age']
scaler = MinMaxScaler()


df[non_boolean_numerical_features] = scaler.fit_transform(df[non_boolean_numerical_features])

#Test

In [330]:
X = df.drop('price', axis=1)
y = df['price']

In [331]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [332]:
from sklearn.linear_model import LinearRegression
linear_reg = LinearRegression()
linear_reg.fit(X_train, y_train)

LinearRegression()

In [333]:
y_pred_train = linear_reg.predict(X_train)
y_pred_test = linear_reg.predict(X_test)

In [334]:
#Import the necessary functions from sklearn
from sklearn.metrics import mean_squared_error, r2_score

train_mse = mean_squared_error(y_train, y_pred_train)
train_r2 = r2_score(y_train, y_pred_train)


test_mse = mean_squared_error(y_test, y_pred_test)
test_r2 = r2_score(y_test, y_pred_test)

print(f"Training MSE:{train_mse}")
print(f"Testing MSE:{test_mse}")
print(f"Training R2 Score:{train_r2}")
print(f"Testing R2 Score:{test_r2}")

Training MSE:0.0005864745857337843
Testing MSE:0.0007265639125049
Training R2 Score:0.08858661505446919
Testing R2 Score:0.07685151261611145

In [335]:
model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

mean_squared_error = mean_squared_error(y_test, y_pred, squared=False)

In [336]:
dt['car_age'] = current_year - dt['model_year'].astype(str).str.split('-', expand=True).astype(int)
dt['transmission_A/T'] = df['transmission_A/T'].astype(int)
dt['transmission_CVT'] = df['transmission_CVT'].astype(int)
dt['transmission_DCT'] = df['transmission_DCT'].astype(int)
dt['transmission_M/T'] = df['transmission_M/T'].astype(int)
dt['accident_No'] = df['accident_No'].astype(int)
dt['accident_Yes'] = df['accident_Yes'].astype(int)
#Verify that the column 'is_luxury_No' exists in the DataFrame 'df'. You may need to correct any typos.


dt.drop(columns=['accident','clean_title','engine', 'ext_col', 'fuel_type', 'id', 'int_col', 'model', 'transmission'], axis=1, inplace=True)

In [337]:
label_encoder = LabelEncoder()
dt['brand'] = label_encoder.fit_transform(dt['brand'])

In [338]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 162610 entries, 0 to 188532
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   brand             162610 non-null  int64
 1   model_year        162610 non-null  float64
 2   milage            162610 non-null  float64
 3   price             162610 non-null  float64
 4   car_age           162610 non-null  float64
 5   transmission_A/T  162610 non-null  bool
 6   transmission_CVT  162610 non-null  bool
 7   transmission_DCT  162610 non-null  bool
 8   transmission_M/T  162610 non-null  bool
 9   accident_No       162610 non-null  bool
 10  accident_Yes      162610 non-null  bool
dtypes: bool(6), float64(4), int64(1)
memory usage: 12.4 MB

In [339]:
dt.fillna(0, inplace=True)

In [340]:
dt.head()

,brand,model_year,milage,car_age,transmission_A/T,transmission_CVT,transmission_DCT,transmission_M/T,accident_No,accident_Yes
0,26,2015,98000,9,1.0,0.0,0.0,0.0,1.0,0.0
1,26,2020,9142,4,1.0,0.0,0.0,0.0,0.0,1.0
2,14,2022,28121,2,1.0,0.0,0.0,0.0,1.0,0.0
3,3,2016,61258,8,0.0,0.0,1.0,0.0,1.0,0.0
4,3,2018,59000,6,1.0,0.0,0.0,0.0,1.0,0.0

In [341]:
id = sf.pop('id')
y_pred = model.predict(dt)

# Create a submission DataFrame
submission_df = pd.DataFrame({
    'id': id,
    'class': y_pred
})

# Save the submission DataFrame to a CSV file
submission_df.to_csv('submission_file.csv', index=False)
print("Submission file created: submission_file.csv")

Submission file created: submission_file.csv